import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Head from 'next/head'
import { Box, Text, Heading, Button, HStack, VStack, Stack } from '@chakra-ui/react'
import { CloseIcon} from '@chakra-ui/icons'
import CharacterList from '../../components/characters/CharacterList'
import ReactPaginate from 'react-paginate';
import Router, { withRouter } from 'next/router'
import { useEffect, useState } from 'react'
import axios from 'axios'
import useSWR from "swr"

type Character = {
  title: string
}

type PeopleProps = {
    next: string;
    results: {
        [key: string]: Character
    };
}

const fetcher = (url:string) => axios.get(url).then(res => res.data)
//  count: 82,
//   next: 'https://swapi.dev/api/people/?page=2',
//   previous: null,

const People: NextPage = ({ fallback }:any) => {
  const { data }  = (useSWR(`/api/characters`, fetcher) || fallback)
  console.log(data)
    const [isLoading, setLoading] = useState(false); //State for the loading indicator
    const startLoading = () => setLoading(true);
    const stopLoading = () => setLoading(false);
    // const numOfPages = Math.ceil(data.count / 10)

  //   useEffect(() => { //After the component is mounted set router event handlers
  //     Router.events.on('routeChangeStart', startLoading); 
  //     Router.events.on('routeChangeComplete', stopLoading);

  //     return () => {
  //         Router.events.off('routeChangeStart', startLoading);
  //         Router.events.off('routeChangeComplete', stopLoading);
  //     }
  // }, [])

    const pagginationHandler = (page:any) => {
      // const currentPath = Router.pathname;
      // const currentQuery = Router.query;
      // currentQuery.page = page.selected + 1;

      // Router.push({
      //     pathname: currentPath,
      //     query: currentQuery,
      // });

    };

  return (
    <Box align="center">
      <Head>
        <title>Star Wars Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Heading>
          Star Wars Characters
        </Heading>

        <Text>
          All People
        </Text>

        <CharacterList list={data.results}/>
        <Stack direction="column">
          <ReactPaginate
                    previousLabel={'Previous'}
                    nextLabel={'Next'}
                    breakLabel={'...'}
                    activeClassName={'active'}
                    initialPage={1}
                    pageCount={2}
                    pageRangeDisplayed={5}
                    onPageChange={pagginationHandler}
                />
        </Stack>
    </Box>
  )
}

export async function getStaticProps () {
  // `getStaticProps` is executed on the server side.
  const res = await fetch('https://swapi.dev/api/people/');
  const data = await res.json();
  return {
    props: {
      fallback: {
        '/api/characters': data
      }
    }
  }
}

export default People