import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Head from 'next/head'
import { Box, Text, Heading, Stack } from '@chakra-ui/react'
import CharacterList, { CharactersProps } from '../../components/characters/CharacterList'
import { CharacterType } from '../../components/characters/Character';
import ReactPaginate from 'react-paginate';
import Router, { withRouter } from 'next/router'
import { useEffect, useState } from 'react'
import axios from 'axios'
import useSWR, { SWRConfig } from "swr"

export type DataProps = {
  data: {
    count: number,
    next: string | null;
    previous: string | null;
    results: CharacterType[];
  }
}

//  count: 82,
//   next: 'https://swapi.dev/api/people/?page=2',
//   previous: null,

const People = ({ data }: DataProps) => {
  const [isLoading, setLoading] = useState(false); //State for the loading indicator
  const startLoading = () => setLoading(true);
  const stopLoading = () => setLoading(false);
  console.log(data)
  const numOfPages = Math.ceil(data.count / 10)

  useEffect(() => { //After the component is mounted set router event handlers
    Router.events.on('routeChangeStart', startLoading); 
    Router.events.on('routeChangeComplete', stopLoading);
    return () => {
        Router.events.off('routeChangeStart', startLoading);
        Router.events.off('routeChangeComplete', stopLoading);
    }
  }, [])

  // useEffect(() => {
  //   if(!data){
  //   setLoading(true);
  //   }
  // }, [data]);

    const pagginationHandler = (page:any) => {
      const currentPath = Router.pathname;
      const currentQuery = Router.query;
      currentQuery.page = page.selected + 1 ;

      Router.push({
          pathname: currentPath,
          query: currentQuery,
      });

    };

    // if (isLoading) {
    //   return <p>Data is loading...</p>;
    // }
  return (
    <Box align="center">
      <Head>
        <title>Star Wars Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Heading>
          Star Wars Characters
        </Heading>
        <Text>
          All People
        </Text>

        <CharacterList characters={data.results}/>

        <Stack direction="column">
          <ReactPaginate
            previousLabel={'Previous'}
            nextLabel={'Next'}
            breakLabel={'...'}
            activeClassName={'active'}
            initialPage={1}
            pageCount={numOfPages}
            pageRangeDisplayed={5}
            onPageChange={pagginationHandler}
          />
        </Stack>
    </Box>
  )
}

export const getStaticProps = async ()  => {
  try {
    const res = await axios.get("https://swapi.dev/api/people/");

    return {
      props: {
        data: res.data,
      },
    };
  } catch (error) {
    console.log(error);
  }
};


export default People