import type { NextPage, GetStaticProps, InferGetStaticPropsType} from "next";
import Head from "next/head";
import { useState } from "react";
import { Container, Heading } from "@chakra-ui/react";
import SearchBar from "../../components/SearchBar";
import PoemCard, { PoemProps } from "../../components/poem";
import { poemHandler, getSearchedPoems } from "../../utils/searchHandlers";
import axios from "axios";

const Poetry: NextPage = ({ fetchedPoem }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const [poemObj, setPoem] = useState({
    poem: fetchedPoem,
    searchInput: "",
    searchList: [],
  });

  const getSearchHandler = ( e: { target: { value: string | undefined } } ) => {
    getSearchedPoems({ e, axios, poemObj, setPoem })
  };

  const getPoemHandler = ( id: string ) => {
    poemHandler({ id, axios, poemObj, setPoem })
  };

  const { poem, searchInput, searchList } = poemObj;

  return (
    <Container w={[400, 500, 600]} align="center">
        <Head>
            <title>Search For Poetry</title>
            <meta name="Poetry Search" content="Generated by next" />
            <link rel="tabIcon" href="/favicon.ico" />
        </Head>
        <Heading mt={4} fontSize={["sm", "lg", "xl"]}>{ "Search By Poem or Writer" }</Heading>
        <SearchBar
            value={searchInput}
            data={searchList}
            changeHandler={getSearchHandler}
            clickHandler={getPoemHandler}
        />
        <PoemCard poem={poem}/>
    </Container>
  );
};

export const getStaticProps: GetStaticProps = async ( ) => {
  const res = await axios.get("https://poetrydb.org/random");
  const fetchedPoem: PoemProps = await res.data[0];
  return {
    props: {
      fetchedPoem, 
      revalidate: 60 * 60 * 6,
    },
  };
};

export default Poetry;