import type { NextPage, GetStaticProps, GetStaticPropsContext, InferGetStaticPropsType} from "next";
import { useState } from "react";
import { Container, Heading } from "@chakra-ui/react";
import axios from "axios";
import SearchBar from "../../components/SearchBar";
import { poemHandler, pSearchHandler } from "../../utils/coverHandlers";
import PoemCard, { PoemProps } from "../../components/poem";
import Head from "next/head";

const Poetry: NextPage = ({ quote }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const [poemObj, setPoem] = useState({
    searchedInput: "",
    items: [],
    item: quote,
  });

  const getSearchHandler = ( e: { target: { value: string | undefined } } ) => {
    pSearchHandler({ e, axios, poemObj, setPoem })
  };

  const getPoemHandler = ( id: string ) => {
    poemHandler({ id, axios, poemObj, setPoem })
  };

  const { searchedInput, items, item } = poemObj;
  return (
    <Container w={[400, 500, 600]} align="center">
        <Head>
            <title>Search For Poetry</title>
            <meta name="Poetry Search" content="Generated by next" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Heading mt={4} fontSize={["sm", "lg", "xl"]}>{ "Search By Author" }</Heading>
        <SearchBar
            data={items}
            value={searchedInput}
            changeHandler={getSearchHandler}
            clickHandler={getPoemHandler}
        />
        <PoemCard item={item}/>
    </Container>
  );
};

export const getStaticProps: GetStaticProps = async ( context: GetStaticPropsContext ) => {
  const res = await axios.get("https://poetrydb.org/random");
  const quote: PoemProps = await res.data[0];
  return {
    props: {
      quote, 
      revalidate: 60 * 60 * 6,
    },
  };
};

export default Poetry;