import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Head from 'next/head'
import { Box, Divider, Flex, Text } from '@chakra-ui/react'
import axios from 'axios'
import useSWR from 'swr'



export type DataProps = {
  book: {
    publishers: string[];
    number_of_pages: number;
    isbn_10: string[];
    covxers: number[];
    authors: [ { key: string } ];
    key: string;
    ocaid: string;
    contributions: string[];
    languages: [ { key: string } ];
    classifications: {};
    source_records: string[];
    title: string;
    identifiers: { goodreads:  string[], librarything: string[] },
    isbn_13: string[];
    local_id: string[];
    publish_date: string;
    works: [ { key: string; } ],
    type: { key: string; },
    first_sentence: {
      type: string;
      value: string;
    },
    latest_revision: number;
    revision: number;
    created: { type: string, value: string },
    last_modified: { type: string, value: string };
  }
}

const fetcher = (url:string) => axios.get(url).then(res => res.data)

const Books: NextPage = ({ book }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { data, error } = useSWR('/api/book', fetcher)
  console.log(data)
  return (
    <Box align="center">
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction='column'>
        <Text>Name: {book.title}</Text>
        <Divider/>
        <Text>Publisher: {book.publishers}</Text>
        <Divider/>
        <Text>Publish Date: {book.publish_date}</Text>
        <Divider/>
        <Text>Pages: {book.number_of_pages}</Text>
        <Divider/>
        <Text>1st Sentence: {book.first_sentence.value}</Text>
        <Divider/>
      </Flex>

    </Box>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
    // Call an external API endpoint to get posts.
    // You can use any data fetching library
    const res = await axios.get('https://openlibrary.org/isbn/9780140328721')
    const book: DataProps = await res.data
  
    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
      props: {
        book: book,
      },
    }
  }

export default Books