import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Head from 'next/head'
import { Box, Text, Heading, Input, HStack, InputGroup, InputRightElement } from '@chakra-ui/react'
import CoverList from '../components/bookCovers/CoverList'
import axios from 'axios'
import { CoverType } from '../components/bookCovers/CoverCard'
import { SearchIcon } from '@chakra-ui/icons'
import { SetStateAction, useState } from 'react'

export type DataProps = {
  books: {
    key: string | null;
    name: string | null;
    subject_type: string | null;
    work_count: number,
    works: CoverType[];
  }
}

const Books: NextPage = ({ books }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const [value, setValue] = useState('')
  const handleChange = (event: { target: { value: SetStateAction<string> } }) => setValue(event.target.value)
  const onSubmit = () => {
    const searchVal = value.split(" ").join("+");
    setValue('')
  }
  return (
    <Box align="center">
      <Head>
        <title>Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text mb='8px'>Value: {value}</Text>
      <InputGroup align="center" justifyContent="center" size='md'>
        <Input 
          value={value}
          onChange={handleChange}
          placeholder='Search For Books' 
          size='lg' />
        <InputRightElement width='4.5rem'>
          <SearchIcon onClick={onSubmit}/>
        </InputRightElement>
      </InputGroup>
      <CoverList books={books}/> 

    </Box>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
    // Call an external API endpoint to get posts.
    const res = await axios.get(`https://www.googleapis.com/books/v1/volumes?q=harry+potter&key=${process.env.API_KEY}`)
    const books: DataProps = await res.data.items
  console.log(books)
    return {
      props: {
        books: books,
      },
    }
  }

export default Books