import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Head from 'next/head'
import { Box, Text, Heading } from '@chakra-ui/react'
import CoverList from '../components/bookCovers/CoverList'
import styles from '../styles/Films.module.css'
import axios from 'axios'
import { CoverType } from '../components/bookCovers/CoverCard'

export type DataProps = {
  books: {
    key: string | null;
    name: string | null;
    subject_type: string | null;
    work_count: number,
    works: CoverType[];
  }
}

const Books: NextPage = ({ books }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Box align="center">
      <Head>
        <title>Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Heading>
          Search All Books
        </Heading>

        <Text className={styles.description}>
          All Books
        </Text>

        <CoverList   books={books.works}/> 

    </Box>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
    // Call an external API endpoint to get posts.
    const res = await axios.get('https://openlibrary.org/subjects/love.json?limit=10?offset')
    const books: DataProps = await res.data

    return {
      props: {
        books: books,
      },
    }
  }

export default Books