import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { Box, Text, Heading } from '@chakra-ui/react'
import FilmCard from '../components/FilmCard'
import styles from '../styles/Films.module.css'

type Film = {
  title: string
}

type FilmProps = {
    results: {
        [key: string]: Film
    };
}


const Films: NextPage = ({ movies }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>Star Wars Films</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link passHref href="/">
          <button>
          <a>Back</a>
          </button>
        </Link>
        <Heading className={styles.title}>
          Star Wars Films
        </Heading>

        <Text className={styles.description}>
          All Films
        </Text>

        <Box>
            {movies.results.map((film:any) => (
                <FilmCard key={film.title} item={film}/>
            ))}
        </Box>

      </main>
    </Box>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
    // Call an external API endpoint to get posts.
    // You can use any data fetching library
    const res = await fetch('https://swapi.dev/api/films/')
    const movies: FilmProps[] = await res.json()
  
    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
      props: {
        movies: movies,
      },
    }
  }

export default Films