import type { NextPage, GetStaticProps, InferGetStaticPropsType} from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { Box, Text, Heading } from '@chakra-ui/react'
import FilmList from '../components/film/FilmList'
import styles from '../styles/Films.module.css'

type Film = {
  title: string
}

type FilmProps = {
    results: {
        [key: string]: Film
    };
}


const Films: NextPage = ({ movies }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Box align="center">
      <Head>
        <title>Star Wars Films</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Heading>
          Star Wars Films
        </Heading>

        <Text className={styles.description}>
          All Films
        </Text>

        <FilmList movies={movies}/>

    </Box>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
    // Call an external API endpoint to get posts.
    // You can use any data fetching library
    const res = await fetch('https://swapi.dev/api/films/')
    const movies: FilmProps[] = await res.json()
  
    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
      props: {
        movies: movies,
      },
    }
  }

export default Films